# Generated by Django 2.2.1 on 2019-05-29 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageLinkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('css_style', models.CharField(blank=True, default=None, max_length=30, verbose_name='Css стиль')),
                ('css_class', models.CharField(blank=True, choices=[('label_echo_blue', 'label_echo_blue'), ('label_dandelion', 'label_dandelion'), ('label_waikawa_grey', 'label_waikawa_grey'), ('label_tahuna_sands', 'label_tahuna_sands'), ('label_carmine', 'label_carmine'), ('label_kelly_green', 'label_kelly_green'), ('label_boulder', 'label_boulder'), ('label_fuchsia_pink', 'label_fuchsia_pink'), ('label_corious_blue', 'label_corious_blue'), ('label_biloba_flowere', 'label_biloba_flowere'), ('label_mona_lisa', 'label_mona_lisa'), ('label_neurtal_green', 'label_neurtal_green'), ('label_red_orange', 'label_red_orange'), ('label_hot_toddy', 'label_hot_toddy'), ('label_bright_sun', 'label_bright_sun'), ('label_regent_st_blue', 'label_regent_st_blue'), ('label_french_pass', 'label_french_pass')], default=None, max_length=30, verbose_name='Css класс')),
                ('hidden', models.BooleanField(default=False, verbose_name='Спрятать')),
                ('_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('_order',),
            },
        ),
        migrations.CreateModel(
            name='HomepageRegistrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, verbose_name='Название')),
                ('url', models.CharField(default='', max_length=255, verbose_name='Ссылка')),
                ('login_url', models.CharField(blank=True, default=None, max_length=255, verbose_name='Ссылка входа')),
                ('affiliate_url', models.CharField(blank=True, default=None, max_length=255, verbose_name='Партнерская ссылка')),
            ],
            options={
                'verbose_name': 'Регистратор',
                'verbose_name_plural': 'Регистраторы',
            },
        ),
        migrations.CreateModel(
            name='RedmineMonthStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Hours')),
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
            },
        ),
        migrations.CreateModel(
            name='RedmineTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255, verbose_name='Project')),
                ('task', models.CharField(max_length=255, verbose_name='Task')),
                ('task_id', models.IntegerField(verbose_name='Task ID')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='HomepageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('hidden', models.BooleanField(default=False, verbose_name='Спрятать')),
                ('_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.HomepageLinkGroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ('_order',),
            },
        ),
        migrations.CreateModel(
            name='HomepageDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('url', models.CharField(blank=True, default=None, max_length=255, verbose_name='Ссылка')),
                ('expired', models.DateField(default='2000-01-01', verbose_name='Expired')),
                ('registrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.HomepageRegistrar', verbose_name='Регистратор')),
            ],
            options={
                'verbose_name': 'Домен',
                'verbose_name_plural': 'Домены',
            },
        ),
    ]
